module.exports = {
    USER: 'userProfile',
    EDUCATION: 'education',
    WORK_EXPERIENCE: 'workExperience',
    CERTIFICATES: 'certificate',
    TAKING_CLASSES: 'takingClasses',
    CONDUCTING_CLASSES: 'conductingClasses',
    MENTORING: 'mentoring',
    WRITINGS: 'writing',
    CONFERENCES: 'confrences',
    AWARDS: 'awards',
    RECOGNIZED_EXPERTIESE: 'recognizedExpertise',
    PATENTS: 'patents',
    LANGUAGES: 'languages',
    LEISURE_TRAVEL: 'leisureTravel',
    TOOLS: 'tools',
    SKILLS: 'skills',
    POINTS: 'points',
    EDUCATION_SCORE: 'educationScore'
}